spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/blog
    username: root
    password: zz2843517195
  data:
    redis:
      port: 6379
      host: redis
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848