---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 张峥.
--- DateTime: 2024/1/27 22:10
---
local couponId = ARGV[1];
local userId = ARGV[2];

local stockKey = 'coupon:stock:' .. couponId;
local orderKey = 'coupon:order:' .. couponId;

if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1;
end ;

if (redis.call('sismember', orderKey, userId) == 1) then
    return 2;
end

redis.call('incryby', stockKey, -1);
redis.call('sadd', orderKey, userId);

return 0;