---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 张峥.
--- DateTime: 2024/1/24 14:19
---
local key = KEYS[1];
local threadId = ARGV[1];
local releaseTime = ARGV[2];
local maxRetries = ARGV[3];
local retryInterval = ARGV[4];

local retries = 0;

while retries < maxRetries do
    if (redis.call('exists', key) == 0) then
        redis.call('hset', key, threadId, '1');
        redis.call('expire', key, releaseTime);
        return 1;
    end ;

    if (redis.call('hexists', key, threadId) == 1) then
        redis.call('hincrby', key, threadId, '1');
        redis.call('expire', key, releaseTime);
        return 1;
    end ;

    redis.call("msleep", retryInterval);
    retries = retries + 1;
end

return 0;